version: '3.1'

services:
  app:
    tty: true
    image: jjthomson2166/scale-ubuntu
    volumes:
      # coreのバインドマウント
      # - "/home/jjthomson/core:/root/core"
      - type: bind
        source: "/home/jjthomson/core"
        target: "/root/core"
      # scale-5.4.4のバインドマウント
      - type: bind
        source: "/home/jjthomson/scale-5.4.4"
        target: "/root/scale-5.4.4"
      # Fドライブ(移行前)のバインドマウント
      - type: bind
        source: "/mnt/f/ishihara_juntaro/ishihara_master"
        target: "/root/ishihara_master"
      # Fドライブ(移行先)のバインドマウント
      - type: bind
        source: "/mnt/f/ishihara_juntaro/fdrive"
        target: "/root/fdrive"
    # command: bash initial
    # command: ln -s /root/fdrive/scale_database /root/scale-5.4.4/
    # command: export PATH=$PATH:/root/scale-5.4.4/scale-rm/test/tutorial
    # command: export Tutorial_DIR=$HOME/scale-5.4.4/scale-rm/test/tutorial