version: '3.1'

services:
  app:
    tty: true
    image: jjthomson2166/scale-ubuntu
    volumes:
      # coreのバインドマウント
      # - "/home/jjthomson/core:/root/core"
      - type: bind
        source: "/home/jjthomson/core"
        target: "/root/core"
      # Fドライブのバインドマウント
      - type: bind
        source: "/mnt/f/ishihara_juntaro/ishihara_master"
        target: "/root/ishihara_master"
      # scale-5.4.4
      # - "/root/scale-5.4.4"
